### ISSUE TITLE
nest at-rules, pseudo classes and elements

### ISSUE THREAD

**Issue by giuseppeg** [postcss/postcss-js#29]
I am converting some CSS to CSS-in-JS and, in the majority of the implementations, at rules, pseudo classes and elements are nested e.g.

```css
.root {
  color: red;
}
@media screen and (min-width: 5em) {
  .root {
     color: green;
  }
}
```
becomes:

```js
{
  root: {
    color: red,
    '@media screen and (min-width: 5em)': {
      color: 'green',
    },
  },
}
```

Right now postcss-js produces non nested rules instead and I understand why. 

Would you be open to add an option to transform to nested? or do you think that this should be done in user land? 

I figured I'd ask you since 
1) you are more familar with the postcss-js codebase and probably could implement this quickly 
2) if I need to implement this for myself and you think that it'd be nice to have this feature then I could contribute to postcss-js
