### ISSUE TITLE
Media query ordering changes when converting to object

### ISSUE THREAD

**Issue by AlanBreck** [postcss/postcss-js#69]
Given an input like the following:

```css
.button {
	--box-shadow-hover: var(--effect-elevation-02);
	cursor: pointer;
	transition: box-shadow 0.12s ease-in-out, color 0.12s ease-in-out;
	box-shadow: none;
	border: solid var(--border-width, 0px) var(--border-color, transparent);
	border-radius: var(--radius-full);
	background: var(--bg);
	color: var(--color);
}
.button:enabled:hover,
.button:enabled [data-is-button-target]:hover :host .button {
	background: var(--bg-hover, var(--bg));
	color: var(--color-hover, var(--color));
	box-shadow: var(--box-shadow-hover);
}
.button:enabled:active {
	background: var(--bg-active, var(--bg));
	color: var(--color-active, var(--color-hover, var(--color)));
}
.button:enabled:focus-visible {
	outline: none;
	box-shadow: 0px 0px 0px 1.7px rgba(255, 255, 255, 0.75), 1px 1px 4px 2px rgba(95, 103, 215, 0.75),
		-1px -1px 4px 2px rgba(255, 71, 36, 0.75);
	background: var(--bg-focus, var(--bg));
}
.button.isLoading {
	background: var(--bg-loading, var(--bg));
	color: var(--color-loading, var(--color));
}
:host[disabled] .button,
.button[disabled] {
	background: var(--bg-disabled, var(--bg));
}
.button.isSmall {
	--icon-size: 20px;
	font: var(--font-button-small);
	padding: 8px 14px;
}
.button.isMedium {
	--icon-size: 24px;
	font: var(--font-button-default);
	padding: 12px 16px;
}
.button.isLarge {
	--icon-size: 24px;
	font: var(--font-button-large);
	padding: 12px 16px;
}
.button.isPrimary {
	--bg: var(--color-secondary-light-mode-70);
	--bg-hover: var(--color-secondary-light-mode-80);
	--bg-active: var(--color-secondary-light-mode-90);
	--bg-focus: var(--color-secondary-light-mode-70);
	--bg-loading: var(--color-secondary-light-mode-50);
	--bg-disabled: var(--color-gray-70);
	--color: white;
}
@media (prefers-color-scheme: dark) {
	.button.isPrimary {
		--bg: var(--color-secondary-dark-mode-50);
		--bg-hover: var(--color-secondary-dark-mode-60);
		--bg-active: var(--color-secondary-dark-mode-70);
		--bg-loading: var(--color-secondary-dark-mode-60);
	}
}
.button.isSecondary {
	--bg: white;
	--bg-active: --color-gray-20;
	--color: var(--color-gray-90);
	--color-hover: var(--color-secondary-light-mode-70);
	--color-loading: var(--color-gray-70);
	--border-width: 1px;
	--border-color: var(--color-gray-30);
}
.button.isSecondary[disabled] {
	opacity: 0.5;
}
@media (prefers-color-scheme: dark) {
	.button.isSecondary {
		--bg: black;
		--color-hover: var(--color-secondary-dark-mode-80);
	}
}
.isTertiary {
	border-radius: 8px;
	--color: var(--color-secondary-70);
	--color-hover: var(--color-secondary-80);
	--color-active: var(--color-secondary-90);
	--color-loading: var(--color-secondary-50);
	--box-shadow-hover: none;
}
.button.isCTA {
	--bg: var(--gradient-gradient-04);
}
```

The output is

```json
{
	".leoButton": {
		"--box-shadow-hover": "var(--effect-elevation-02)",
		"cursor": "pointer",
		"transition": "box-shadow 0.12s ease-in-out, color 0.12s ease-in-out",
		"boxShadow": "none",
		"border": "solid var(--border-width, 0px) var(--border-color, transparent)",
		"borderRadius": "var(--radius-full)",
		"background": "var(--bg)",
		"color": "var(--color)"
	},
	".leoButton:enabled:hover,.leoButton:enabled [data-is-button-target]:hover :host .leoButton": {
		"background": "var(--bg-hover, var(--bg))",
		"color": "var(--color-hover, var(--color))",
		"boxShadow": "var(--box-shadow-hover)"
	},
	".leoButton:enabled:active": {
		"background": "var(--bg-active, var(--bg))",
		"color": "var(--color-active, var(--color-hover, var(--color)))"
	},
	".leoButton:enabled:focus-visible": {
		"outline": "none",
		"boxShadow": "0px 0px 0px 1.7px rgba(255, 255, 255, 0.75), 1px 1px 4px 2px rgba(95, 103, 215, 0.75), -1px -1px 4px 2px rgba(255, 71, 36, 0.75)",
		"background": "var(--bg-focus, var(--bg))"
	},
	".leoButton.isLoading": {
		"background": "var(--bg-loading, var(--bg))",
		"color": "var(--color-loading, var(--color))"
	},
	":host[disabled] .leoButton,.leoButton[disabled]": {
		"background": "var(--bg-disabled, var(--bg))"
	},
	".leoButton.isSmall": {
		"--icon-size": "20px",
		"font": "var(--font-button-small)",
		"padding": "8px 14px"
	},
	".leoButton.isMedium": {
		"--icon-size": "24px",
		"font": "var(--font-button-default)",
		"padding": "12px 16px"
	},
	".leoButton.isLarge": {
		"--icon-size": "24px",
		"font": "var(--font-button-large)",
		"padding": "12px 16px"
	},
	".leoButton.isPrimary": {
		"--bg": "var(--color-secondary-light-mode-70)",
		"--bg-hover": "var(--color-secondary-light-mode-80)",
		"--bg-active": "var(--color-secondary-light-mode-90)",
		"--bg-focus": "var(--color-secondary-light-mode-70)",
		"--bg-loading": "var(--color-secondary-light-mode-50)",
		"--bg-disabled": "var(--color-gray-70)",
		"--color": "white"
	},
	"@media (prefers-color-scheme: dark)": [
		{
			".leoButton.isPrimary": {
				"--bg": "var(--color-secondary-dark-mode-50)",
				"--bg-hover": "var(--color-secondary-dark-mode-60)",
				"--bg-active": "var(--color-secondary-dark-mode-70)",
				"--bg-loading": "var(--color-secondary-dark-mode-60)"
			}
		},
		{
			".leoButton.isSecondary": {
				"--bg": "black",
				"--color-hover": "var(--color-secondary-dark-mode-80)"
			}
		}
	],
	".leoButton.isSecondary": {
		"--bg": "white",
		"--bg-active": "--color-gray-20",
		"--color": "var(--color-gray-90)",
		"--color-hover": "var(--color-secondary-light-mode-70)",
		"--color-loading": "var(--color-gray-70)",
		"--border-width": "1px",
		"--border-color": "var(--color-gray-30)"
	},
	".leoButton.isSecondary[disabled]": {
		"opacity": 0.5
	},
	".isTertiary": {
		"borderRadius": "8px",
		"--color": "var(--color-secondary-70)",
		"--color-hover": "var(--color-secondary-80)",
		"--color-active": "var(--color-secondary-90)",
		"--color-loading": "var(--color-secondary-50)",
		"--box-shadow-hover": "none"
	},
	".leoButton.isCTA": {
		"--bg": "var(--gradient-gradient-04)"
	}
}
```

The problem here is that `.leoButton.isSecondary` gets placed after the media query, which changes the behavior of the rendering.

Is this a known bug? Is there any known fix for this?
